Update generate_json.yml

diff --git a/.github/workflows/generate_json.yml b/.github/workflows/generate_json.yml
--- a/.github/workflows/generate_json.yml
+++ b/.github/workflows/generate_json.yml
@@ -28,6 +28,10 @@ jobs:
       - name: Generate JSON
         run: node generate_json.js  # Ajusta el nombre del script si es necesario
 
+      - name: Generate JSON
+        run: python generate_json.py || echo "Error during script execution"
+
+
       - name: Commit and Push Changes
         run: |
           git config --global user.email "actions@github.com"
